[profile.default]
src = "src"
out = "out"
libs = ["dependencies", "lib"]
via_ir = true
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"


[invariant]
runs = 1
depth = 512
seed = '0x3e8'


[lint]
lint_on_build = false
